import { createRequestHandler } from "@react-router/cloudflare";
// @ts-expect-error - Server build generated by React Router
import * as serverBuild from "../build/server/index.js";

const requestHandler = createRequestHandler({
  build: serverBuild,
  mode: "production",
});

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return requestHandler({
      request,
      env,
      waitUntil: ctx.waitUntil.bind(ctx),
      passThroughOnException: ctx.passThroughOnException.bind(ctx),
    });
  },
} satisfies ExportedHandler<Env>;
