import { createRequestHandler } from "@react-router/cloudflare";
// @ts-expect-error - Server build generated by React Router
import * as serverBuild from "../build/server/index.js";

const requestHandler = createRequestHandler({
  build: serverBuild,
  mode: "production",
});

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    try {
      return await requestHandler({
        request,
        env,
        waitUntil: ctx.waitUntil.bind(ctx),
        passThroughOnException: ctx.passThroughOnException.bind(ctx),
      });
    } catch (error) {
      console.error("Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
} satisfies ExportedHandler<Env>;
