import { createRequestHandler } from "@react-router/cloudflare";
// @ts-expect-error - Server build generated by React Router
import * as serverBuild from "../build/server/index.js";

const requestHandler = createRequestHandler({
  build: serverBuild,
  mode: "production",
});

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    try {
      const url = new URL(request.url);

      // Handle /app/* routes - SPA routing for desktop app
      if (url.pathname.startsWith("/app")) {
        // Try to fetch static asset
        const assetResponse = await env.ASSETS.fetch(request);
        if (assetResponse.status !== 404) {
          return assetResponse;
        }
        // Fallback to /app/index.html for SPA routing
        const indexRequest = new Request(
          new URL("/app/index.html", request.url),
          request
        );
        return await env.ASSETS.fetch(indexRequest);
      }

      return await requestHandler({
        request,
        env,
        waitUntil: ctx.waitUntil.bind(ctx),
        passThroughOnException: ctx.passThroughOnException.bind(ctx),
      });
    } catch (error) {
      console.error("Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
} satisfies ExportedHandler<Env>;
